services:
  db:
    image: mongo:7
    volumes:
      - type: volume
        source: mydb
        target: /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  server:
    build: .
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    environment:
      - MONGO_PWD
      - MONGO_USERNAME
volumes:
  mydb:
    external: true